server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitwithme?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  profiles:
    include: private
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: ${JWT_SECRET_KEY}
  accessTokenValidity: 7200000
  refreshTokenValidity: 86400000

