server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitwithme?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true